POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJldmFudGhAZ21haWwuY29tIiwiZXhwIjoxNzQ3NjM4ODc5LCJ1c2VySWQiOjJ9.ceDY5QyXWsvkV9Kpd7wmQy1VGSD1B_OAGDyb-dqyQf0

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}